from tkinter import*
import pickle
import os
import time
nameList=pickle.load(open("name.dat","rb"))
activityList=pickle.load(open("activity.dat","rb"))
timeList=pickle.load(open("time.dat","rb"))
os.system("clear")
root=Tk()
root.geometry("500x600")
root.title("Activity List")
root.config(bg="CadetBlue1")
title=Label(root,text="Activity List",font=("times",15,"bold"),bg="CadetBlue1")
title.place(relx=0.5,rely=0.05,anchor=CENTER)
label4=Label(root,text="Name:",font=("times",15),bg="CadetBlue1")
label4.place(relx=0.3,rely=0.7,anchor=CENTER)
labelName=Label(root,text="",font=("times",15,"bold"),bg="CadetBlue1")
labelName.place(relx=0.7,rely=0.7,anchor=CENTER)
label5=Label(root,text="Activity:",font=("times",15),bg="CadetBlue1")
label5.place(relx=0.3,rely=0.75,anchor=CENTER)
labelActivity=Label(root,text="",font=("times",15,"bold"),bg="CadetBlue1")
labelActivity.place(relx=0.7,rely=0.75,anchor=CENTER)
label6=Label(root,text="Time:",font=("times",15),bg="CadetBlue1")
label6.place(relx=0.3,rely=0.8,anchor=CENTER)
labelTime=Label(root,text="",font=("times",15,"bold"),bg="CadetBlue1")
labelTime.place(relx=0.7,rely=0.8,anchor=CENTER)
label1=Label(root,text="Name:",font=("times",15),bg="CadetBlue1")
label1.place(relx=0.3,rely=0.4,anchor=CENTER)
nameInput=Entry(root,font=("times",12),bg="CadetBlue1")
nameInput.place(relx=0.7,rely=0.4,anchor=CENTER)
label2=Label(root,text="Activity:",font=("times",15),bg="CadetBlue1")
label2.place(relx=0.3,rely=0.45,anchor=CENTER)
activityInput=Entry(root,font=("times",12),bg="CadetBlue1")
activityInput.place(relx=0.7,rely=0.45,anchor=CENTER)
label3=Label(root,text="Time:",font=("times",15),bg="CadetBlue1")
label3.place(relx=0.3,rely=0.5,anchor=CENTER)
timeInput=Entry(root,font=("times",12),bg="CadetBlue1")
timeInput.place(relx=0.7,rely=0.5,anchor=CENTER)
def Add():
    global nameList
    global activityList
    global timeList
    val1=nameInput.get()
    val2=activityInput.get()
    val3=timeInput.get()
    nameList.append(val1)
    activityList.append(val2)
    timeList.append(val3)
    pickle.dump(nameList,open("name.dat","wb"))
    print("Name:")
    print(nameList)
    pickle.dump(activityList,open("activity.dat","wb"))
    print("Activity:")
    print(activityList)
    pickle.dump(timeList,open("time.dat","wb"))
    print("Time:")
    print(timeList)
def Clear():
    nameList.clear()
    activityList.clear()
    timeList.clear()
    pickle.dump(nameList,open("name.dat","wb"))
    pickle.dump(activityList,open("activity.dat","wb"))
    pickle.dump(timeList,open("time.dat","wb"))
    print("Name:")
    print(nameList)
    print("Activity:")
    print(activityList)
    print("Time:")
    print(timeList)
def Show():
    labelName["text"]=str(nameList)
    labelActivity["text"]=str(activityList)
    labelTime["text"]=str(timeList)
btnAdd=Button(root,text="Save",command=Add,font=("times",12),fg="medium spring green")
btnAdd.place(relx=0.2,rely=0.6,anchor=CENTER)
btnClear=Button(root,text="Clear",command=Clear,font=("times",12),fg="medium spring green")
btnClear.place(relx=0.5,rely=0.6,anchor=CENTER)
btnShow=Button(root,text="Show",command=Show,font=("times",12),fg="medium spring green")
btnShow.place(relx=0.8,rely=0.6,anchor=CENTER)
root.mainloop()